# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - DimaApp

on:
  push:
    branches:
      - main
    paths:
      - Dima.Api/**
  workflow_dispatch:

env:
  ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_SERVER_CONNECTION_STRING }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      
      - name: Install EF Tools
        run: dotnet tool install --global dotnet-ef

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get IP
        id: ip
        uses: haythem/public-ip@v1.3 

      - name: Add Firewall Rule For IP
        run: az sql server firewall-rule create --resource-group "Dima" --server "dima-iuri" --name "ghactions" --start-ip-address ${{ steps.ip.outputs.ipv4 }}  --end-ip-address ${{ steps.ip.outputs.ipv4 }}
      
      - name: Update database
        run: dotnet ef database update --project Dima.Api/Dima.Api.csproj

      - name: Delete Firewall Rule
        run: az sql server firewall-rule delete --resource-group "Dima" --server "dima-iuri" --name "ghactions"

      - name: Build with dotnet
        run: dotnet build Dima.Api/Dima.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish Dima.Api/Dima.Api.csproj -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./myapp
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F833D763CA084E799E5476F29BDC3A4D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7966E49A3335474FAE4FC772E1741434 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_068E3BE557414779B8DB56D8121A6329 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DimaApi'
          slot-name: 'Production'
          package: ./myapp
          